extern newdata1
;extern newdata2

extern background
extern projxmul
extern projymul
extern projxadd
extern projyadd
extern projminz
extern projminzshr
extern wminx
extern wminy
extern wmaxx
extern wmaxy
extern vram
extern rowsadd
extern truerowsadd
extern truevram
extern glenz_rows
extern framerate10
extern color
extern color1
extern color2
extern video
extern borders

extern _xadd
extern _yadd
extern _zadd

