name: build-all
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download and install Free Pascal
      run: |
        echo "Downloading Free Pascal..."
        curl https://downloads.freepascal.org/fpc/dist/3.2.2/i386-win32/fpc-3.2.2.i386-win32.exe -o fpc-3.2.2.i386-win32.exe
        echo "Installing Free Pascal..."
        ./fpc-3.2.2.i386-win32.exe /VERYSILENT /ALLUSERS
        echo "Waiting for install to finish..."
        Wait-Process -Name "fpc-3.2.2.i386-win32"
        echo "Done!"
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build Debug|X86
      run: msbuild .\SecondRealityW32.sln /p:Configuration=Debug /p:Platform=x86
    - name: Build Release|X86
      run: msbuild .\SecondRealityW32.sln /p:Configuration=Release /p:Platform=x86
